platform :ios, '10.0'
use_frameworks!

target 'Demo' do
  pod 'ViperMcFlurryX'
  pod 'CacheTracker'
  pod 'CacheTracker/CoreData'
  pod 'CacheTrackerConsumer'
  pod 'CacheTrackerConsumer/UIKit'
  pod 'TransparentProxyViewController'
  pod 'RamblerSegues'
  pod 'OnDeallocateX'
  pod 'ViperServices'
  pod 'RxSwift'
  pod 'ReSwift'
  pod 'DefaultsKit'

  target 'DemoTests' do
    inherit! :complete
  end
end
