platform :ios, '10.0'
use_frameworks!

target 'Demo' do
  pod 'ViperMcFlurryX', '>= 1.8.3'
  pod 'CacheTracker'
  pod 'CacheTracker/CoreData'
  pod 'CacheTrackerConsumer', '>= 1.5.0'
  pod 'CacheTrackerConsumer/UIKit'
  pod 'TransparentProxyViewController'
  pod 'RamblerSegues'
  pod 'OnDeallocateX'
  pod 'ViperServices'
  pod 'RxSwift'
  pod 'ReSwift'
  pod 'DefaultsKit'
  pod 'MagicalRecord'

  target 'DemoTests' do
    inherit! :complete
  end
end

pre_install do |installer|
  installer.analysis_result.specifications.each do |s|
    s.swift_version = '4.2' unless s.swift_version
  end
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['SWIFT_VERSION'] = '4.2'
  end
end
