version: 1.1.0
xcodeVersion: 13.0
name: Demo
options:
  bundleIdPrefix: com.test
targets:
  Demo:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    sources:
      - Demo
    dependencies:
      - target: DemoTests
    scheme:
      testTargets:
        - DemoTests
    settings:
      INFOPLIST_FILE: Info.plist
      SWIFT_VERSION: "4.2"
      ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: "$(inherited)"
  DemoTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "13.0"
    settings:
      SWIFT_VERSION: "4.2"
    sources:
      - path: Demo
        excludes:
          - "Sources/AppDelegate.swift"
          - "Sources/*.storyboard"
